[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lsfm-data-processing"
version = "0.2.0"
description = "Reusable utilities and scripts for LSFM data processing workflows"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
dependencies = [
  "numpy",
  "opencv-python",
  "tifffile",
  "pillow",
  "nibabel"
]

[project.optional-dependencies]
registration = [
  "atlasspace @ git+https://github.com/ingvildeb/atlasspace.git@v0.2.0"
]

[tool.setuptools.packages.find]
include = ["lsfm_data_processing*"]

[tool.setuptools.package-data]
"lsfm_data_processing.registration_and_transforms.batch_registration.hpc" = ["*.sh"]
"lsfm_data_processing.registration_and_transforms.batch_registration.config_templates" = ["*.toml"]
"lsfm_data_processing.registration_and_transforms.sweep_registration.hpc" = ["*.sh"]
"lsfm_data_processing.registration_and_transforms.sweep_registration.config_templates" = ["*.toml"]
